import setmodule
s1=set(map(int,input("Enter the elements of set1:").split()))
s2=set(map(int,input("Enter the elements of set2:").split()))
uni=setmodule.sunion(s1,s2)
print("Union :",uni)
inter=setmodule.sintersection(s1,s2)
print("Intersection :",inter)
diff=setmodule.sdifference(s1,s2)
print("Difference :",diff)
sdiff=setmodule.ssymmetricdiff(s1,s2)
print("Symmetric Difference :",sdiff)
